# Generated by Django 4.2 on 2023-07-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'db_table': 'tracker_location',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Arm Status',
                'db_table': 'tracker_status',
            },
        ),
        migrations.CreateModel(
            name='ArmType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('manufacture_date', models.CharField(max_length=200)),
                ('purchase_country', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('semi_auto', 'Semi Automatic'), ('lever_action', 'Lever Action'), ('fully_automatic', 'Fully Automatic'), ('close_bolt', 'Close Bolt'), ('break_action', 'Break Action'), ('revolver', 'Revolver'), ('pistol_single_shot', 'Pistol Single Shot'), ('gas_operated', 'Gas Operated'), ('open_bolt', 'Open Bolt'), ('brech_load', 'Brech Load'), ('single_shot', 'Single Shot'), ('artillery', 'Artillery'), ('gas_regulated', 'Gas Regulated')], max_length=200)),
                ('license_category', models.CharField(choices=[('long_arm', 'Long Arm'), ('handgun', 'Handgun'), ('sport_shooting', 'Sport Shooting'), ('hunting', 'Hunting')], max_length=200)),
                ('genuine_reason', models.CharField(blank=True, choices=[('rfmf_personnel', 'RFMF Personnel'), ('navy_personnel', 'Navy Personnel'), ('police_personnel', 'Police Personnel'), ('civillian_personnel', 'Civillian Personnel')], max_length=200)),
                ('source', models.CharField(blank=True, choices=[('confiscated', 'Confiscated'), ('previously_unregistered', 'Previously Unregistered'), ('surrendered', 'Surrendered'), ('imported', 'Imported')], max_length=200)),
                ('remarks', models.TextField(blank=True, max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arms.location')),
            ],
            options={
                'verbose_name_plural': 'Arms',
                'db_table': 'tracker_armtype',
            },
        ),
        migrations.CreateModel(
            name='ArmIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regimental_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(choices=[('major_general', 'Major General'), ('rear_admiral', 'Rear Admiral'), ('brigadier', 'Brigadier'), ('commodore', 'Commodore'), ('colonel', 'Colonel'), ('lt_colonel', 'LT Colonel'), ('major', 'Major'), ('chief_of_navy', 'Chief of Navy'), ('padre', 'Padre'), ('captain', 'Captain'), ('commander', 'Commander'), ('lt_commander', 'LT Commander'), ('leutenant ', 'Leutenant'), ('sub_leutenant', 'Sub Leutenant'), ('ensign', 'Ensign'), ('midshipman', 'Midshipman'), ('cadet', 'Cadet'), ('warrant_officer_I', 'Warrant Officer I'), ('warrant_officer_II', 'Warrant Officer II'), ('staff_sergeant', 'Staff Sergeant'), ('sergeant', 'Sergeant'), ('corporal', 'Corporal'), ('lance_corporal', 'Lance Corporal'), ('private', 'Private'), ('leutenant ', 'Leutenant'), ('rsm_army', 'RSM Army'), ('master_arm_navy', 'Master at Arm Navy'), ('ordinary_seaman', 'Ordinary Seaman Navy')], max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('unit', models.CharField(max_length=200)),
                ('ammunition_status', models.CharField(choices=[('damage', 'Damage'), ('dispose', 'Dispose'), ('expended', 'Expended'), ('issue', 'Issue'), ('returned', 'Returned'), ('expired', 'Expired')], max_length=50)),
                ('license_type', models.CharField(max_length=200)),
                ('archive_reason', models.CharField(blank=True, max_length=200)),
                ('id_types', models.CharField(blank=True, choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('rfmf_id', 'RFMF ID'), ('police_id', 'Police ID')], max_length=200)),
                ('arm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arms.armtype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arms.location')),
            ],
            options={
                'verbose_name_plural': 'Arms Issued Out',
                'db_table': 'tracker_arm',
            },
        ),
    ]
