# Generated by Django 4.2 on 2023-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0002_remove_armtype_genuine_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='armtype',
            name='status',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('misplaced', 'Misplaced'), ('serviceable', 'Serviceable'), ('unserviceable', 'Unserviceable'), ('held_for_destruction', 'Held For Destruction'), ('destroyed', 'Destroyed'), ('return', 'Return'), ('registered', 'Registered')], max_length=200),
        ),
    ]
