# Generated by Django 4.2 on 2023-07-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0003_delete_status_alter_armtype_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Serial Numbers',
                'db_table': 'tracker_serialnumber',
            },
        ),
        migrations.AlterField(
            model_name='armissue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='armtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='armissue',
            table='tracker_armissue',
        ),
        migrations.AddField(
            model_name='armissue',
            name='serial_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arm_issues', to='arms.serialnumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armtype',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arm_types', to='arms.serialnumber'),
        ),
    ]
