# Generated by Django 4.2 on 2023-07-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0005_alter_armissue_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('misplaced', 'Misplaced'), ('serviceable', 'Serviceable'), ('unserviceable', 'Unserviceable'), ('held_for_destruction', 'Held For Destruction'), ('destroyed', 'Destroyed'), ('return', 'Return'), ('registered', 'Registered')], max_length=200)),
                ('manufacture_date', models.CharField(max_length=200)),
                ('purchase_country', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('semi_auto', 'Semi Automatic'), ('lever_action', 'Lever Action'), ('fully_automatic', 'Fully Automatic'), ('close_bolt', 'Close Bolt'), ('break_action', 'Break Action'), ('revolver', 'Revolver'), ('pistol_single_shot', 'Pistol Single Shot'), ('gas_operated', 'Gas Operated'), ('open_bolt', 'Open Bolt'), ('brech_load', 'Brech Load'), ('single_shot', 'Single Shot'), ('artillery', 'Artillery'), ('gas_regulated', 'Gas Regulated')], max_length=200)),
                ('license_category', models.CharField(choices=[('long_arm', 'Long Arm'), ('handgun', 'Handgun'), ('sport_shooting', 'Sport Shooting'), ('hunting', 'Hunting')], max_length=200)),
                ('source', models.CharField(blank=True, choices=[('confiscated', 'Confiscated'), ('previously_unregistered', 'Previously Unregistered'), ('surrendered', 'Surrendered'), ('imported', 'Imported')], max_length=200)),
                ('remarks', models.TextField(blank=True, max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arms.location')),
            ],
            options={
                'verbose_name_plural': 'Arms',
                'db_table': 'tracker_arm',
            },
        ),
        migrations.RemoveField(
            model_name='armtype',
            name='location',
        ),
        migrations.RemoveField(
            model_name='armtype',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='armissue',
            name='serial_number',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='SerialNumber',
        ),
        migrations.AlterField(
            model_name='armissue',
            name='arm_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arms.arm'),
        ),
        migrations.DeleteModel(
            name='ArmType',
        ),
    ]
