# Generated by Django 4.2 on 2023-07-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0008_alter_armissue_arm_type_alter_armissue_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm',
            name='name',
            field=models.CharField(choices=[('revolver', 'Revolver'), ('pistol', 'Pistol'), ('holster', 'Holster'), ('machine_gun', 'Machine Gun'), ('shot_gun', 'Shot Gun'), ('rifle', 'Rifle'), ('air_gun', 'Air Gun'), ('grenade_launcher', 'Grenade Launcher'), ('smg', 'SMG'), ('lmg', 'LMG'), ('mortar', 'Mortar'), ('craft_gun', 'Craft Gun'), ('sniper_rifle', 'Sniper Rifle')], max_length=200),
        ),
    ]
